upstream web_app {
    server web:8000;
}

map $host $acme_root {
    darabazaar.com /var/www/darabazaar.com;
    www.darabazaar.com /var/www/www.darabazaar.com;
}

server {
    listen 80;
    server_name darabazaar.com www.darabazaar.com;

    client_max_body_size 100M;

    # اگر می‌خواهی برای Let's Encrypt چک/renewal کار کند
    location /.well-known/acme-challenge/ {
        root $acme_root;
        default_type text/plain;
    }

    # ریدایرکت همه چیز به HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name darabazaar.com www.darabazaar.com;

    client_max_body_size 100M;

    ssl_certificate     /etc/letsencrypt/live/darabazaar.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/darabazaar.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 1024;

    gzip_types
        text/plain
        text/css
        text/xml
        application/json
        application/javascript
        application/xml
        application/rss+xml
        application/atom+xml
        image/svg+xml;

    location / {
        proxy_pass http://web_app;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}