# Generated by Django 6.0.4 on 2026-08-06 00:08

import django.utils.timezone
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_news', models.ImageField(blank=True, null=True, upload_to=news.models.news_cover_upload_path)),
                ('alt_img', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=450)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
