# Generated by Django 6.0.4 on 2026-04-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
