# Generated by Django 6.0.4 on 2026-05-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0004_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='title',
            new_name='users_total_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
