# Generated by Django 6.0.4 on 2026-05-05 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0005_rename_title_useraddress_users_total_name_and_more'),
        ('Products', '0011_remove_productmedia_is_video_productmedia_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('new', 'آکبند'), ('used', 'کارکرده')], default='new')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerAccount.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
            options={
                'unique_together': {('order', 'product', 'condition')},
            },
        ),
    ]
