# Generated by Django 6.0.4 on 2026-05-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0006_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
