# Generated by Django 6.0.4 on 2026-05-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0007_alter_user_email'),
        ('Products', '0011_remove_productmedia_is_video_productmedia_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='Products.product'),
        ),
    ]
