# Generated by Django 6.0.4 on 2026-05-08 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0008_user_wishlist'),
        ('Products', '0014_alter_product_about_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product'),
        ),
    ]
