# Generated by Django 6.0.4 on 2026-05-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0010_cart_cartitem_cart_unique_active_cart_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
