# Generated by Django 6.0.4 on 2026-05-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0011_remove_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
