# Generated by Django 6.0.4 on 2026-05-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0012_remove_cartitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_text',
            field=models.TextField(null=True),
        ),
    ]
