# Generated by Django 6.0.4 on 2026-05-13 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0013_order_address_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'آدرس کاربر', 'verbose_name_plural': 'آدرس\u200cهای کاربر'},
        ),
        migrations.AddField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='users_total_name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
    ]
