# Generated by Django 6.0.4 on 2026-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0014_alter_useraddress_options_useraddress_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='condition',
            field=models.CharField(choices=[('new', 'آکبند'), ('used', 'کارکرده')], default='new', max_length=20),
        ),
    ]
