# Generated by Django 6.0.4 on 2026-07-29 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0015_alter_orderdetail_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomerAccount.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='blupal', max_length=20)),
                ('invoice_id', models.BigIntegerField(unique=True)),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (ریال)')),
                ('final_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ نهایی (ریال)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('EXPIRED', 'منقضی شده'), ('CANCELED', 'لغو شده'), ('FAILED', 'ناموفق')], default='PENDING', max_length=20)),
                ('payment_link', models.URLField(blank=True)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('raw_create_response', models.JSONField(blank=True, null=True)),
                ('raw_webhook_response', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='CustomerAccount.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
