# Generated by Django 6.0.4 on 2026-08-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0016_order_address_order_created_at_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال (تومان)'),
        ),
    ]
