# Generated by Django 6.0.4 on 2026-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccount', '0017_order_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=150000, verbose_name='هزینه ارسال (تومان)'),
        ),
    ]
