# Generated by Django 6.0.4 on 2026-04-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_remove_cart_session_key_alter_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
