# Generated by Django 6.0.4 on 2026-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomePage', '0003_remove_cartitem_cart_remove_cartitem_product_and_more'),
        ('Products', '0018_alter_productmedia_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, related_name='bestsellers', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, related_name='latest', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, related_name='trending', to='Products.product')),
            ],
        ),
    ]
