# Generated by Django 6.0.4 on 2026-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='gamebg',
            field=models.ImageField(blank=True, null=None, upload_to='trending', verbose_name='پس\u200cزمینه بازی'),
        ),
        migrations.AddField(
            model_name='trending',
            name='gameimage',
            field=models.ImageField(blank=True, null=None, upload_to='trending', verbose_name='کاور بازی'),
        ),
    ]
