# Generated by Django 6.0.4 on 2026-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_trending_gamebg_trending_gameimage'),
        ('Products', '0025_rename_discount_product_discount_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, related_name='bestDeals', to='Products.product')),
            ],
        ),
    ]
