# Generated by Django 6.0.4 on 2026-06-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_bestdeals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=None, upload_to='hero', verbose_name='هیرو هوم')),
            ],
        ),
    ]
