# Generated by Django 6.0.4 on 2026-06-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='text',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
