# Generated by Django 6.0.4 on 2026-07-05 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_alter_hero_text'),
        ('Products', '0025_rename_discount_product_discount_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='Products.product'),
        ),
    ]
