# Generated by Django 6.0.4 on 2026-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'اکشن'), ('Adventure', 'ماجراجویی'), ('RPG', 'نقش\u200cآفرینی'), ('Shooter', 'شوتر'), ('Horror', 'ترسناک'), ('Sports', 'ورزشی'), ('Strategy', 'استراتژی'), ('Racing', 'مسابقه\u200cای')], max_length=20)),
                ('developer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('file_size_gb', models.FloatField()),
                ('summary', models.TextField()),
                ('cover_image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
