# Generated by Django 6.0.4 on 2026-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('Action', 'اکشن'), ('Adventure', 'ماجراجویی'), ('RPG', 'نقش\u200cآفرینی'), ('Shooter', 'شوتر'), ('Horror', 'ترسناک'), ('Sports', 'ورزشی'), ('Strategy', 'استراتژی'), ('Racing', 'مسابقه\u200cای'), ('OpenWord', 'جهان باز')], max_length=20),
        ),
    ]
