# Generated by Django 6.0.4 on 2026-04-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(to='Products.genre'),
        ),
    ]
