# Generated by Django 6.0.4 on 2026-04-16 23:40

from django.db import migrations, models


def forwards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE "Products_product" ALTER COLUMN "release_date" '
            'TYPE integer USING (EXTRACT(YEAR FROM release_date)::integer)'
        )
        return
    Product = apps.get_model('Products', 'Product')
    old_field = Product._meta.get_field('release_date')
    new_field = models.IntegerField(null=True)
    schema_editor.alter_field(Product, old_field, new_field)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_genre_remove_product_genre_product_genres'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='product',
                    name='release_date',
                    field=models.IntegerField(null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards, migrations.RunPython.noop),
            ],
        ),
    ]
