# Generated by Django 6.0.4 on 2026-04-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
