# Generated by Django 6.0.4 on 2026-04-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_new',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت نو'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_used',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت کارکرده'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_new',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to='media/products/'),
        ),
    ]
