# Generated by Django 6.0.4 on 2026-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_product_price_new_product_price_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(blank=True, to='Products.genre'),
        ),
    ]
