# Generated by Django 6.0.4 on 2026-04-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_product_price_alter_product_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='is_video',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/products/'),
        ),
    ]
