# Generated by Django 6.0.4 on 2026-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_remove_productmedia_is_video_productmedia_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
