# Generated by Django 6.0.4 on 2026-05-07 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_product_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/about/', verbose_name='عکس اصلی About'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='متن کوتاه About'),
        ),
        migrations.CreateModel(
            name='ProductAboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویژگی (مثلاً Explore a Land...)')),
                ('description', models.TextField(verbose_name='توضیحات ویژگی')),
                ('image', models.ImageField(upload_to='products/about/features/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_features', to='Products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
