# Generated by Django 6.0.4 on 2026-05-08 00:30

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_product_about_main_image_alter_product_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about_main_image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_about_image_upload_path, verbose_name='عکس اصلی About'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='productaboutfeature',
            name='image',
            field=models.ImageField(upload_to=Products.models.product_feature_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.product_media_upload_path),
        ),
    ]
