# Generated by Django 6.0.4 on 2026-05-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_product_about_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about_main_image',
        ),
    ]
