# Generated by Django 6.0.4 on 2026-05-08 01:02

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_remove_product_about_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_main_image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_about_image_upload_path, verbose_name='عکس اصلی About'),
        ),
    ]
