# Generated by Django 6.0.4 on 2026-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_product_about_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
    ]
