# Generated by Django 6.0.4 on 2026-05-12 14:21

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_productmedia_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_thumb_upload_path),
        ),
    ]
