# Generated by Django 6.0.4 on 2026-05-13 16:09

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_alter_productaboutfeature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='فقط برای ویدیو استفاده شود (پیش\u200cنمایش ویدیو)', null=True, upload_to=Products.models.product_thumb_upload_path, verbose_name='تصویر بندانگشتی (فقط ویدیو)'),
        ),
    ]
