# Generated by Django 6.0.4 on 2026-05-13 16:11

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_alter_productmedia_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaboutfeature',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات ویژگی'),
        ),
        migrations.AlterField(
            model_name='productaboutfeature',
            name='image',
            field=models.ImageField(null=True, upload_to=Products.models.product_feature_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productaboutfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productaboutfeature',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان ویژگی (مثلاً Explore a Land...)'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_thumb_upload_path),
        ),
    ]
