# Generated by Django 6.0.4 on 2026-05-13 16:14

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_alter_productaboutfeature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaboutfeature',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات ویژگی'),
        ),
        migrations.AlterField(
            model_name='productaboutfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_feature_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productaboutfeature',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productaboutfeature',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان ویژگی (مثلاً Explore a Land...)'),
        ),
    ]
