# Generated by Django 6.0.4 on 2026-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_new',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_used',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
