# Generated by Django 6.0.4 on 2026-07-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_rename_discount_product_discount_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system',
            field=models.CharField(choices=[('ps1', 'ps1'), ('ps2', 'ps2'), ('ps3', 'ps3'), ('ps4', 'ps4'), ('ps5', 'ps5'), ('xbox', 'xbox'), ('Nintendo', 'Nintendo')], default='ps5', max_length=8),
        ),
    ]
