# Generated by Django 6.0.4 on 2026-07-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_product_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='player',
            field=models.CharField(choices=[('single', 'یک نفره'), ('two', 'دو نفره'), ('multiplayer', 'چند نفره')], default='single', max_length=12),
        ),
    ]
