# Generated by Django 6.0.4 on 2026-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_product_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='player',
            field=models.CharField(choices=[('singleplayer', 'یک نفره'), ('twoplayer', 'دو نفره'), ('multiplayer', 'چند نفره')], default='singleplayer', max_length=12),
        ),
    ]
