# Generated by Django 6.0.4 on 2026-08-05 23:05

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_alter_product_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image_products_page',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to=Products.models.product_cover_upload_path),
        ),
    ]
