# Generated by Django 6.0.4 on 2026-08-06 18:27

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0030_product_cover_image_products_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image_products_page',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_cover_upload_path),
        ),
    ]
